# DISPLAY CONFIG
DISPLAY_WIDTH = int(3440)
DISPLAY_HEIGHT = int(1440)

# CROPPING CONFIG
XY_CROP_SNAP_INCREMENT = float(100.0)
Z_CROP_SNAP_INCREMENT = float(100.0)

# CUBIFICATION CONFIG
CUBE_DIM_X = int(100)
CUBE_DIM_Y = int(100)
CUBE_DIM_Z = int(100)




